### ISSUE TITLE
SHACL shapes for current RML

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-fno-spec#35]
@DylanVanAssche and @pmaria should already have some shapes, let's start with these, what they cover and what they don't and how they need to be adjusted to fit to the new spec of RML.

**Comment by DylanVanAssche** [comment]
@dachafra @andimou Is there a specific location where we can put the shapes?
- Separate repo in kg-construct?
- Inside the spec repo?
- `<your suggestion>`

**Comment by andimou** [comment]
I'll just write down here so we keep track, we agreed on including them within the spec repo
