### ISSUE TITLE
predicate could be a blank node?

### ISSUE THREAD

**Issue by srodriguez142857** [kg-construct/rml-fno-spec#41]
The RML spec states the following:
> Both **predicate maps** and **object maps** are _term maps_.

But a _term map_ can be a _blank node_.

Would this be "misleading"?
Does this mean that a predicate could be a blank node?
Obviously, this is not correct: a predicate should only be an IRI.

![image](https://user-images.githubusercontent.com/9869215/138705985-f8b71cc9-3c2c-4b98-8b3e-bc7d34ea7558.png)

**Comment by dachafra** [comment]
@anaigmo is this already solved in the diagrams?

**Comment by anaigmo** [comment]
I left a note clarifying it, it will be solved with the constrains

**Comment by dachafra** [comment]
ok, so we can close this as @anaigmo already takes it :-)
