### ISSUE TITLE
Add section for implementation considerations

### ISSUE THREAD

**Issue by pmaria** [kg-construct/rml-fno-spec#6]
There are several considerations that can be made when implementing RML+FnO. Some of these might need to be specified in their own section, others might be too specific too certain implementations, but might still be interesting to mention. For now we can add a section 'Implementation considerations' to collect these, as discussed in [this slack thread](https://kg-construct.slack.com/archives/C01QFSW77QF/p1616768778002200)

Examples of issues:
* Handling programming language specific datatypes
* Special handling of RDF term types in used software library (e.g. from RDFJS, JENA, etc)
  * e.g. what if a function returns an RDF literal with language tag?
* What should an engine do with the generated FnO execution triples (from the function triples map)?

**Comment by bjdmeest** [comment]
I created #8, #9, #10, to discuss the individual issues separately, and added a section in the spec :)
